config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :authors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get "/authors", to: "authors#index", as: "authors"
  # post "/authors", to: "authors#create"
  # get "/authors/new", to: "authors#new", as: "new_author"
  # get "/authors/:id", to: "authors#show", as: "author"

  # patch "/authors/:id", to: "authors#update"
  # put "/authors/:id", to: "authors#update"
  # delete "/authors/:id", to: "authors#destroy"
  # get "/authors/:id/edit", to: "authors#edit", as: "edit_author"

  get "/", to: "books#index", as: "books"
  post "/", to: "books#create"
  get "/new", to: "books#new", as: "new_book"
  get "/:id", to: "books#show", as: "book"

  patch "/:id", to: "books#update"
  put "/:id", to: "books#update"
  delete "/:id", to: "books#destroy"
  get "/:id/edit", to: "books#edit", as: "edit_book"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :author
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_one :address, dependent: :destroy
  # has_one :address, class_name: "Address", foreign_key: "author_id"
  has_many :books, dependent: :destroy
  # destroy--if we delete author all dependents e.g. addres books deleted
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :books_genres
  has_many :genres, through: :books_genres
  belongs_to :user
end

app/models/books_genre.rb
class BooksGenre < ApplicationRecord
  belongs_to :book
  belongs_to :genre
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :books_genres
  has_many :books, through: :books_genres
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @authors = Author.all
  end

  def create
    @name = params[:name]
    @date_of_birth = params[:date_of_birth]
    Author.create(name: @name, date_of_birth: @date_of_birth)
    redirect_to authors_path
  end

  def new
  end

  def show
    @author = Author.find(params[:id])
    @books = @author.books
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    @author.name = params[:name]
    @author.date_of_birth = params[:date_of_birth]
    @author.save
    redirect_to author_path
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    redirect_to authors_path
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @books = Book.all
    @authors = Author.all
  end

  def create
    @author = params[:author]
    @title = params[:title]
    @description = params[:description]
    @current_user = current_user.id

    @new_book = Author.find_by(name: @author).books.create(title: @title, description: @description, user_id: @current_user)
    @genre_ids = params[:genres]
    @genre_ids.each { |genre_id| @new_book.genres << Genre.find(genre_id) }

    redirect_to books_path
  end

  def new
    @authors = Author.all
    @author_names = Author.all.collect(&:name)
    @genres = Genre.all
  end

  def show
    @book = Book.find(params[:id])
    @author = @book.author.name
  end

  def edit
    @authors = Author.all
    @books = Book.all
    @book = Book.find(params[:id])
    @author_id = Book.find(params[:id]).author_id
    @author_name = Author.find(@author_id).name
    @genres = Genre.all
    @selected_genres = @book.genres.pluck(:name)
  end

  def update
    @book = Book.find(params[:id])
    @book.title = params[:title]
    @book.description = params[:description]
    @book.genres = []
    @genre_ids = params[:genres]
    @genre_ids.each { |genre_id| @book.genres << Genre.find(genre_id) }
    @book.save
    redirect_to book_path
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to books_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/edit.html.erb
<div class="container">
  <h1>Edit Author</h1>
  <nav>
    <%= link_to("View Books", books_path) %> / <%= link_to("View Authors", authors_path) %> / <%= link_to("Add a Book", new_book_path) %>
  </nav>
  <div class="content">
    <form action="<%= author_path %>" method="POST">
      <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" />
      <input type="hidden" name="_method" value="patch" />
      <div class="form-flex">
        <div class="label">
          <label for="name">Author name</label>
        </div>
        <div class="input">
          <input type="text" name="name" id="name" value="<%= @author.name %>">
        </div>
        <div class="label">
          <label for="dob">Author's D.O.B.</label>
        </div>
        <div class="input">
          <input type="date" name="date_of_birth" id="dob" value="<%= @author.date_of_birth %>">
        </div>
        <div class="label"></div>
        <div class="input">
          <input type="submit" class="buttons" value="Edit Author">
        </div>
      </div>
    </form>
  </div>
</div>

app/views/authors/index.html.erb
<div class="container">
  <h1>Authors</h1>
  <nav>
    <%= link_to("View Books", books_path) %> / <%= link_to("View Authors", authors_path) %> / <%= link_to("Add a Book", new_book_path) %>
  </nav>
  <div class="content">
    <% @authors.each do |author| %>
      <ul>
        <li><%= link_to(author.name, author_path(author.id)) %></li>
      </ul>
    <% end %>
  </div>
</div>

app/views/authors/new.html.erb
<div class="container">
  <h1>Add Author</h1>
  <nav>
    <%= link_to("View Books", books_path) %> / <%= link_to("View Authors", authors_path) %> / <%= link_to("Add a Book", new_book_path) %>
  </nav>
  <div class="content">
    <form action="<%= authors_path %>" method="POST">
     <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" />
      <div class="form-flex">
        <div class="label">
          <label for="name">Author name</label>
        </div>
        <div class="input">
          <input type="text" name="name" id="name">
        </div>
        <div class="label">
          <label for="name">Author's D.O.B.</label>
        </div>
        <div class="input">
          <input type="date" name="date_of_birth" id="name">
        </div>
        <div class="label"></div>
        <div class="input">
          <input type="submit" class="buttons" value="Add Author">
        </div>
      </div>
    </form>
  </div>
</div>

app/views/authors/show.html.erb
<div class="container">
  <h1><%= @author.name %></h1>
  <div class="content">
  <%= link_to("Back", :back) %> / <%= link_to("All Authors", authors_path) %>
    <div class="form-flex">
      <div class="label">Name</div>
      <div class="input"><%= @author.name %></div>
      <div class="label">Date of Birth</div>
      <div class="input"><%= @author.date_of_birth %></div>
      <div class="label">Books</div>
      <div class="input">
        <% @books.each do |book| %>
          <ul>
            <li><%= book.title %></li>
          </ul>
        <% end %>
      </div>
      <div class="label"></div>
      <div class="input"><%= link_to("Edit", edit_author_path(params[:id])) %> / <%= link_to("Delete", author_path(params[:id]), method: :delete, data: { confirm: 'Are you sure? This will delete all associated books.' }) %></div>
    </div>
  </div>
</div>

app/views/books/edit.html.erb
<div class="container">
  <h1>Edit Book</h1>
  <nav>
    <%= link_to("View Books", books_path) %> / <%= link_to("View Authors", authors_path) %> / <%= link_to("Add a Book", new_book_path) %>
  </nav>
  <div class="content">

    <form action="<%= book_path %>" method="POST">
      <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" />
      <input type="hidden" name="_method" value="patch" />
        <div class="form-flex">
          <div class="label">
            <label for="author">Author</label>
          </div>
          <div class="input">
            <select name="author" id="author">
              <% @authors.each do |author| %>
                <% if author.name == @author_name  %>
                <option value="<%= author.name %>" selected="selected"><%= author.name %></option>
                <% else %>
                <option value="<%= author.name %>"><%= author.name %></option>
                <% end %>
              <% end %>
            </select>
          </div>
          <div class="label"></div>
          <div class="input">
            Author not on the list?<br>
            <%= link_to("Add an Author", new_author_path) %>!
          </div>
          <div class="label">
            <label for="title">Book title</label>
          </div>
          <div class="input">
            <input type="text" name="title" id="title" value="<%= @book.title %>">
          </div>
          <div class="label">
            <label for="genre">Genre</label>
          </div>
          <div class="input">
              <% @genres.each do |genre| %>
                <ul>
                  <% if @selected_genres.include?(genre.name) %>
                    <li><input class="checkbox" type="checkbox" name="genres[]" id="<%= genre.id %>" value="<%= genre.id %>" checked> <label for="<%= genre.id %>"><%= genre.name %></label></li>
                  <% else %>
                    <li><input class="checkbox" type="checkbox" name="genres[]" id="<%= genre.id %>" value="<%= genre.id %>"> <label for="<%= genre.id %>"><%= genre.name %></label></li>
                  <% end %>
                </ul>
              <% end %>
          </div>
          <div class="label">
            <label for="description">Description</label>
          </div>
          <div class="input">
            <textarea name="description" id="description"><%= @book.description %></textarea>
          </div>
          <div class="label"></div>
          <div class="input">
            <input type="submit" value="Update Book">
          </div>
        </div>
    </form>
  </div>
</div>

app/views/books/index.html.erb
<div class="container"> 
  <h1>Books</h1>
  <nav>
    <%= link_to("View Books", books_path) %> / <%= link_to("View Authors", authors_path) %> / <%= link_to("Add a Book", new_book_path) %>
  </nav>
  <div class="content">
    <div class="flex-table">
      
        <% @authors.each do |author| %>
         <div class="box">
            <h3><%= author.name %></h3>
            <% author.books.each do |book| %>
                <ul>
                  <li><%= link_to(book.title, book_path(book.id)) %></li>
                </ul>
            <% end %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="container">
  <h1>Add a Book</h1>
  <nav>
    <%= link_to("View Books", books_path) %> / <%= link_to("View Authors", authors_path) %> / <%= link_to("Add a Book", new_book_path) %>
  </nav>
  <div class="content">
    <form action="<%= books_path %>" method="POST">
      <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" />
        <div class="form-flex">
          <div class="label">
            <label for="author">Author</label>
          </div>
          <div class="input">
            <select name="author" id="author">
              <% @author_names.each do |author| %>
                <option value="<%= author %>"><%= author %></option>
              <% end %>
            </select>
          </div>
          <div class="label"></div>
          <div class="input">
            Author not on the list?<br>
            <%= link_to("Add an Author", new_author_path) %>!
          </div>
          <div class="label">
            <label for="title">Book Title</label>
          </div>
          <div class="input">
            <input type="text" name="title" id="title">
          </div>
          <div class="label">
            <label for="genre">Genre</label>
          </div>
          <div class="input">
              <% @genres.each do |genre| %>
                <ul>
                  <li><input class="checkbox" type="checkbox" name="genres[]" id="<%= genre.id %>" value="<%= genre.id %>"> <label for="<%= genre.id %>"><%= genre.name %></label></li>
                </ul>
              <% end %>
          </div>
          <div class="label">
            <label for="description">Description</label>
          </div>
          <div class="input">
            <textarea name="description" id="description"></textarea>
          </div>
          <div class="label"></div>
          <div class="input">
            <input type="submit" value="Add Book">
          </div>
        </div>
    </form>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <h1><%= @book.title %></h1>
  <div class="content">
  <%= link_to("Back", :back) %> / <%= link_to("All Books", books_path) %>
    <div class="form-flex">
      <div class="label">Title</div>
      <div class="input"><%= @book.title %></div>
      <div class="label">Author</div>
      <div class="input"><%= @author %></div>
      <div class="label">Genre</div>
      <div class="input">
        <% @book.genres.each do |genre| %>
          <ul>
            <li><%= genre.name %></li>
          </ul>
        <% end %>
      </div>
      <div class="label">Description</div>
      <div class="input"><%= @book.description %></div>
      <div class="label"></div>
      <div class="input"><%= link_to("Edit", edit_book_path(params[:id])) %> / <%= link_to("Delete", book_path(params[:id]), method: :delete, data: { confirm: 'Are you sure?' }) %></div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssociationsLesson</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>